# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 378fde3cd08f81cf90a8064075b2738578c234244934befc34a95318404bdd5062ff578999657a35e655e48681263f5729ba2707d793734a75a524805aadf812

test:
  secret_key_base: 8c42626ed35bd4301148fc6bff896d103df6ce2311e87401e21a566d3dd995b97145ae3de2d629e7ee61a3336539e3d4f9b102a1010e43fd06409d690ed9872d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
